profile: dry_run
ckpt: /root/catkin_ws/src/real_ws/seeker-dev/experiments/cleanup_table_d2/real_policy/real_rvt2_cleanup_table_d2_seed_0/checkpoints/latest.ckpt
task: cleanup_table_d2
name: real_rvt2_dry_run
eval_name: in-domain
calib: all_cams_calib.json
result_log_dir: evaluation/
seed: 0
n_rollouts: 20
horizon: 1000
live_viz: true
